name: apply-label

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    if: github.event.label.name == 'deploy'

    steps:

      - name: Setup
        run: |
          if [[ ! "${GITHUB_BASE_REF}" =~ ^env\/.* ]]; then >&2 echo "error"; exit 1; fi

          echo ::set-env name=PLATFORM    ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f2)
          echo ::set-env name=ENVIRONMENT ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
          echo ::set-env name=REGION      ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)

      - name: Verify
        run: |
          echo "Deployed to ${PLATFORM}/${ENVIRONMENT}/${REGION}!"

  rollback:
    name: Rollback
    runs-on: ubuntu-latest
    
    if: github.event.label.name == 'deploy'

    steps:

      - name: Setup
        run: |
          if [[ ! "${GITHUB_BASE_REF}" =~ ^env\/.* ]]; then >&2 echo "error"; exit 1; fi

          echo ::set-env name=PLATFORM    ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f2)
          echo ::set-env name=ENVIRONMENT ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
          echo ::set-env name=REGION      ::$(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)

      - name: Verify
        run: |
          echo "Rolled back from ${PLATFORM}/${ENVIRONMENT}/${REGION}!"