name: apply-label

on:
  pull_request:
    types: [labeled]

jobs:

  deploy:
    name: Process command
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 0.12.26

    steps:

      - name: Setup
        run: |
          if [[ ! "${GITHUB_BASE_REF}" =~ ^env\/.* ]]; then >&2 echo "error"; exit 1; fi

          echo ::set-env name=PLATFORM::    $(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
          echo ::set-env name=ENVIRONMENT:: $(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)
          echo ::set-env name=REGION::      $(echo ${GITHUB_BASE_REF} | cut -d'/' -f5)

      - name: Check
        run: |
          printenv

          echo "${{ toJson(github) }}"
          echo "---"
          echo "${{ toJson(env) }}"
