name: bot

on:
  issue_comment:
    types: [created]

env:
  BOT_USER: '${{ secrets.BOT_USER }}'
  BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
  BOT_EMAIL: '${{ secrets.BOT_EMAIL }}'

jobs:

  trigger:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '@fedjabosnic')
    
    outputs:
      command: ${{ steps.check.outputs.command }}
      base: ${{ steps.check.outputs.base }}
      head: ${{ steps.check.outputs.head }}
    
    steps:
      - name: check
        id: check
        env:
          COMMENT_BODY: '${{ github.event.comment.body }}'
          URL_PULL_REQUEST:  '${{ github.event.issue.pull_request.url }}'
        run: |
          PULL_REQUEST=$(curl ${URL_PULL_REQUEST} -u fedjabosnic:${BOT_TOKEN})
          echo ::set-output name=command::${COMMENT_BODY//@fedjabosnic /}
          echo ::set-output name=base::$(echo ${PULL_REQUEST} | jq -r '.base')
          echo ::set-output name=head::$(echo ${PULL_REQUEST} | jq -r '.head')


  hello:
    runs-on: ubuntu-latest
    needs: trigger

    if: needs.trigger.outputs.command == '/hello'

    steps:
      - name: hi
        id: hi
        env:
          URL_REACTION:  '${{ github.event.comment.url }}/reactions'
        run: |
          REACTION=$(curl ${URL_REACTION} -u bot:${BOT_TOKEN} -d '{"content": "eyes"}' -H 'Accept: application/vnd.github.squirrel-girl-preview+json')

  merge:
    runs-on: ubuntu-latest
    needs: trigger

    if: needs.trigger.outputs.command == '/merge'

    steps:
      
      - name: pull code
        id: pull
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ needs.trigger.outputs.base.ref }}

      - name: merge
        id: merge
        env:
          HEAD_SHA: ${{ needs.trigger.outputs.head.sha }}
        run: |
          git merge ${HEAD_SHA} --ff-only

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
