name: deploy

on:
  repository_dispatch:
    types: [deploy-command]

jobs:

  deploy:
    name: Process command
    runs-on: ubuntu-latest
    steps:

      - name: Pull code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.BASE_REF }}

      - name: Create deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          environment: ${{ github.event.client_payload.pull_request.base.ref }}
          auto_merge: false

      - name: Set deployment status to 'in progress'
        id: start_deployment
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: ${{ github.event.client_payload.pull_request.base.ref }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: in_progress
          mediaType: '{"previews": ["flash", "ant-man"]}'

      - name: Deploy to '${{ github.event.client_payload.pull_request.base.ref }}'
        run: |
          # deployment logic goes here
          sleep 10
          exit 0

      - name: Set deployment status
        if: always()
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: ${{ github.event.client_payload.pull_request.base.ref }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          mediaType: '{"previews": ["ant-man"]}'
          state: ${{ job.status }}

      - name: Confirm success
        if: success()
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket

      - name: Confirm failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: -1
          body: |
            > Failed to deploy, please check the logs [here][1]

            [1]: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}