name: deployment

on:
  pull_request:
    types: [labeled, unlabeled]

env:
  STACKS: "zookeeper cassandra kafka storm efid school"
  TF_VERSION: 0.12.26

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          printenv
          echo "${{ toJson(github) }}}"
          echo "${{ toJson(env) }}"

  deploy:
    name: deploy ${{ github.base_ref }}
    if: startsWith(github.base_ref, 'env/') && github.event.action == 'labeled' && github.event.label.name =='deploy'

    runs-on: ubuntu-latest

    steps:

      - name: Pull code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ env.BASE_REF }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.1.0
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Deploy stacks
        run: |
          PLATFORM=$(echo ${GITHUB_BASE_REF} | cut -d'/' -f2)
          ENVIRONMENT=$(echo ${GITHUB_BASE_REF} | cut -d'/' -f3)
          REGION=$(echo ${GITHUB_BASE_REF} | cut -d'/' -f4)

          for stack in ${STACKS}
          do
            echo "make apply platform=${PLATFORM} environment=${ENVIRONMENT} region=${REGION} stack=$stack"
          done

      - name: verify
        run: |
          echo "Deployed to ${PLATFORM}/${ENVIRONMENT}/${REGION}!"
