name: hello

on:
  repository_dispatch:
    types: [hello-command]

jobs:
  
  acknowledge:
    name: Acknowledge 'hello' command
    runs-on: ubuntu-latest
    steps:

      - name: Acknowledge
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: eyes

  action:
    name: Process 'hello' command
    runs-on: ubuntu-latest
    needs: acknowledge
    steps:

      - name: Say hi back
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            Hi @${{github.event.client_payload.github.payload.comment.user.login}}!

  confirm:
    name: Confirm outcome
    runs-on: ubuntu-latest
    needs: action
    steps:

      - name: Confirm success
        if: needs.action.result == 'success'
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: rocket

      - name: Confirm failure
        if: needs.action.result == 'failure'
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: -1
          body: |
            [Command run output][1]

            [1]: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}