name: hello

on:
  repository_dispatch:
    types: [hello-command]

jobs:
  
  action:
    name: Process 'hello' command
    runs-on: ubuntu-latest
    steps:

      - name: Say hi back
        uses: peter-evans/create-or-update-comment@v1.4.2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.pull_request.number }}
          reaction-type: +1
          body: |
            Hi @${{github.event.client_payload.github.payload.comment.user.login}}!
